name: Build and Deploy

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --immutable
    
    - name: Build
      run: yarn build

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: ./dist
        retention-days: 1
        overwrite: true
  
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    needs: build 

    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4

      - name: Deploy to Hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home/c/${{ secrets.FTP_USER }}/eugene_runet/public_html/
